services:
  request.builder:
    class: RestClient\RequestBuilder
    arguments:
      $parameterBag: '@parameter_bag'

  RestClient\Interfaces\RequestBuilderInterface: '@request.builder'

  restclient:
    class: RestClient\RestClient
    arguments:
      $httpClient: '@http_client'
      $serializer: '@serializer'
      $logger: '@?monolog.logger.http_client'

  RestClient\Interfaces\RestClientInterface: '@restclient'

  make.entity:
    class: RestClient\Maker\MakeRequestEntity
    arguments:
      $parameterBag: '@parameter_bag'
    tags:
      - 'maker.command'