services:
  request.builder:
    class: RestClient\RequestBuilder
    arguments:
      $parameterBag: '@parameter_bag'

  RestClient\Interfaces\RequestBuilderInterface: '@request.builder'

  helper.logger:
    class: RestClient\Helper\LoggerHelper
    arguments:
      $logger: '@monolog.logger.restClient'
      $serializer: '@serializer'
      $parameterBag: '@parameter_bag'

  helper.cache:
    class: RestClient\Helper\CacheHelper
    arguments:
      $cache: '@cache.app'

  restclient:
    class: RestClient\RestClient
    arguments:
      $httpClient: '@http_client'
      $serializer: '@serializer'
      $cacheHelper: '@helper.cache'
      $loggerHelper: '@helper.logger'

  shortrestclient:
    class: RestClient\ShortRestClient
    arguments:
      $restClient: '@restclient'
      $requestBuilder: '@request.builder'

  RestClient\ShortRestClient: '@shortrestclient'
  RestClient\Interfaces\RestClientInterface: '@restclient'

  make.entity:
    class: RestClient\Maker\MakeRequestEntity
    arguments:
      $parameterBag: '@parameter_bag'
    tags:
      - 'maker.command'