services:
  request.builder:
    class: RestClient\RequestBuilder
    arguments:
      $parameterBag: '@parameter_bag'

  RestClient\RequestBuilderInterface: '@request.builder'

  make.entity:
    class: RestClient\Maker\MakeRequestEntity
    arguments:
      $parameterBag: '@parameter_bag'
    tags:
      - 'maker.command'